/**
 * @constant {object} errorConfig
 * @description 故障配置
 */
const errorConfig = {
  data() {
    return {
      ErrorCode_0: [
        {
          errIndex: 1,
          itemId: 1,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E001',
          title: this.$language('error.notify_fault_name_ysxywgz'),
          text: this.$language('error.notify_fault_resolve_ysxywgz'),
        },
        {
          errIndex: 2,
          itemId: 2,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E002',
          title: this.$language('error.notify_fault_name_csxtwgz'),
          text: this.$language('error.notify_fault_resolve_csxtwgz'),
        },
        {
          errIndex: 3,
          itemId: 4,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E003',
          title: this.$language('error.notify_fault_name_ysbgzgz'),
          text: this.$language('error.notify_fault_resolve_ysbgzgz'),
        },
        {
          errIndex: 4,
          itemId: 8,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E004',
          title: this.$language('error.notify_fault_name_ysbybgzgz'),
          text: this.$language('error.notify_fault_resolve_ysbybgzgz'),
        },
        {
          errIndex: 5,
          itemId: 16,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E005',
          title: this.$language('error.notify_fault_name_zybgzgz'),
          text: this.$language('error.notify_fault_resolve_zybgzgz'),
        },
        {
          errIndex: 6,
          itemId: 32,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E006',
          title: this.$language('error.notify_fault_name_zjbybgzgz'),
          text: this.$language('error.notify_fault_resolve_zjbybgzgz'),
        },
        {
          errIndex: 7,
          itemId: 64,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E007',
          title: this.$language('error.notify_fault_name_jlbgzgz'),
          text: this.$language('error.notify_fault_resolve_jlbgzgz'),
        },
        {
          errIndex: 8,
          itemId: 128,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E008',
          title: this.$language('error.notify_fault_name_sxdxxjc'),
          text: this.$language('error.notify_fault_resolve_sxdxxjc'),
        },
      ],
      ErrorCode_1: [
        {
          errIndex: 1,
          itemId: 1,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E009',
          title: this.$language('error.notify_fault_name_ysxywtxgz'),
          text: this.$language('error.notify_fault_resolve_ysxywtxgz'),
        },
        {
          errIndex: 2,
          itemId: 2,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E010',
          title: this.$language('error.notify_fault_name_csxywtxgz'),
          text: this.$language('error.notify_fault_resolve_csxywtxgz'),
        },
        {
          errIndex: 3,
          itemId: 4,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E011',
          title: this.$language('error.notify_fault_name_fstmqytxgz'),
          text: this.$language('error.notify_fault_resolve_fstmqytxgz'),
        },
        {
          errIndex: 4,
          itemId: 8,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E012',
          title: this.$language('error.notify_fault_name_ysbhytxgz'),
          text: this.$language('error.notify_fault_resolve_ysbhytxgz'),
        },
        {
          errIndex: 5,
          itemId: 16,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E013',
          title: this.$language('error.notify_fault_name_fstmqylgg'),
          text: this.$language('error.notify_fault_resolve_fstmqylgg'),
        },
        {
          errIndex: 6,
          itemId: 32,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E014',
          title: this.$language('error.notify_fault_name_glsjqgz'),
          text: this.$language('error.notify_fault_resolve_glsjqgz'),
        },
        {
          errIndex: 7,
          itemId: 64,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E015',
          title: this.$language('error.notify_fault_name_csxsjgz'),
          text: this.$language('error.notify_fault_resolve_csxsjgz'),
        },
        {
          errIndex: 8,
          itemId: 128,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E016',
          title: this.$language('error.notify_fault_name_zlsszbdb'),
          text: this.$language('error.notify_fault_resolve_zlsszbdb'),
        },
      ],
      ErrorCode_2: [
        {
          errIndex: 1,
          itemId: 1,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E017',
          title: this.$language('error.notify_fault_name_csszbdb'),
          text: this.$language('error.notify_fault_resolve_csszbdb'),
        },
        {
          errIndex: 2,
          itemId: 2,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E018',
          title: this.$language('error.notify_fault_name_sgcxsjsdcw'),
          text: this.$language('error.notify_fault_resolve_sgcxsjsdcw'),
        },
        {
          errIndex: 3,
          itemId: 4,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E019',
          title: this.$language('error.notify_fault_name_tgcxsjcw'),
          text: this.$language('error.notify_fault_resolve_tgcxsjcw'),
        },
        {
          errIndex: 4,
          itemId: 8,
          subtitle: this.$language('error.subtitle'),
          headtitle: this.$language('error.headtitle'),
          code: 'E020',
          title: this.$language('error.notify_fault_name_xhsjsjsdcw'),
          text: this.$language('error.notify_fault_resolve_xhsjsjsdcw'),
        },
      ],
    };
  },
};

export default errorConfig;
